sudo: required
dist: trusty
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev

install:
  - sudo apt-get update
  # install liblo before pyliblo
  - sudo apt-get -qq install python3 python3-dev
  # upgrade pip itself
  - pip3 install --upgrade pip
  # install to publish documentation from push or tag
  - pip3 install travis-sphinx
  # build a python wheel
  - python3 setup.py bdist_whell --universal
  # install the package itself
  - pip3 install -ve .
  # install virtual x11 window for testing the app
  - pip3 install pytest-xvfb

script:
  # build the documentation
  - travis-sphinx build

after_success: 
  - travis-sphinx deploy
  - cd tests
  - coveralls

deploy:
  - provider: releases
    file_glob: true
    file: dist/pxst_widgets*.whl
    skip_cleanup: true
    draft: false
    prerelease: false
    on:
      repo: PixelStereo/pxst-widgets
      tags: true
